services:
  mysql:
    image: mysql:8.4
    container_name: mysql8
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpw
      MYSQL_DATABASE: jobproj_db
      MYSQL_USER: db_user
      MYSQL_PASSWORD: db_password
    volumes:
      - mysql8-data:/var/lib/mysql

volumes:
  mysql8-data:
