services:
  mysql8:
    image: mysql:8.4
    container_name: mysql8
    ports:
      - "3307:3306"


    environment:
      MYSQL_DATABASE: jobproj_db
      MYSQL_USER: db_user
      MYSQL_PASSWORD: db_password
      MYSQL_ROOT_PASSWORD: root_password
      TZ: Asia/Seoul
    volumes:
      - ./db/init:/docker-entrypoint-initdb.d
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data: