server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/jobproj_db?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=utf8
    username: ${DB_USERNAME:db_user}
    password: ${DB_PASSWORD:db_password}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connectionInitSql: "SET NAMES utf8mb4"
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false

management:
  endpoints:
    web:
      base-path: /api
      exposure:
        include: health,info
  health:
    db:
      enabled: false